# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{lost_fm}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Alvaro Gil"]
  s.date = %q{2010-11-28}
  s.description = %q{Library to access LastFM api.}
  s.email = %q{zevarito@gmail.com}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "README.md",
     "Rakefile",
     "VERSION",
     "lib/lost_fm.rb",
     "lib/lost_fm/base.rb",
     "lib/lost_fm/error.rb",
     "lib/lost_fm/meta.rb",
     "lost_fm.gemspec",
     "test/test_helper.rb",
     "test/unit/artists_test.rb",
     "test/unit/base_test.rb",
     "test/unit/errors_test.rb"
  ]
  s.homepage = %q{http://github.com/zevarito/lost_fm}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{lost_fm}
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Library to access LastFM api.}
  s.test_files = [
    "test/test_helper.rb",
     "test/unit/artists_test.rb",
     "test/unit/base_test.rb",
     "test/unit/errors_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<json>, [">= 0"])
      s.add_runtime_dependency(%q<hashie>, [">= 0"])
      s.add_development_dependency(%q<contest>, [">= 0"])
      s.add_development_dependency(%q<fakeweb>, [">= 0"])
    else
      s.add_dependency(%q<json>, [">= 0"])
      s.add_dependency(%q<hashie>, [">= 0"])
      s.add_dependency(%q<contest>, [">= 0"])
      s.add_dependency(%q<fakeweb>, [">= 0"])
    end
  else
    s.add_dependency(%q<json>, [">= 0"])
    s.add_dependency(%q<hashie>, [">= 0"])
    s.add_dependency(%q<contest>, [">= 0"])
    s.add_dependency(%q<fakeweb>, [">= 0"])
  end
end

